### ISSUE TITLE
Java Issues

### ISSUE THREAD

**Issue by ThatUserIsTaken** [BLCM/BLCMods#1063]
When attempting to launch BLCMM i get a error from the Java Virtual Machine Launcher "A java exception has occured". What can i do to get it working, i've tried reinstalling java and downloading both 32 and 64 bit versions.

**Comment by nicmr** [comment]
Relevant crash output:
```powershell
PS C:\Games\Steam\steamapps\common\Borderlands 2> java -jar .\BLCMM_Launcher.exe
java.lang.NullPointerException
        at logging.GlobalLogger.findMethod(GlobalLogger.java:120)
        at logging.GlobalLogger.passThrough(GlobalLogger.java:109)
        at logging.GlobalLogger.log(GlobalLogger.java:58)
        at blcmm_launcher.LauncherBackend.<clinit>(LauncherBackend.java:94)
        at blcmm_launcher.Launcher.<clinit>(Launcher.java:33)
Exception in thread "main" java.lang.ExceptionInInitializerError
        at blcmm_launcher.Launcher.<clinit>(Launcher.java:33)
Caused by: java.lang.NullPointerException
        at logging.GlobalLogger.log(GlobalLogger.java:60)
        at blcmm_launcher.LauncherBackend.<clinit>(LauncherBackend.java:94)
        ... 1 more
```

**Comment by ThatUserIsTaken** [comment]
Thank you for the quick response i was unaware that there was a broken release, issue is now solved with a redownload from dropbox.
